### ISSUE TITLE
Exporting simple whole EEG-level data features.

### ISSUE THREAD

**Issue by janbrogger** [bwrc/ctap#6]
I can't output simple whole EEG-level data using the export_features_CTAP function, such as the length of the EEG in seconds. The export functions seem to require a SEGMENT variable. The ATTK data format is undocumented (or rather, the URLs refer to local network URLs that are inaccessible to external users).

We're testing a CTAP pipeline for our dataset of around 10,000 clinical SCORE-annotated EEGs. Before committing to further work, we'd like to see that we can use the exported features in downstream statistical analysis (ideally in Stata). We need an output format of one line per EEG, and some simple descriptive data in columns. Can you help?

I've gotten the simple runctap_minimal working for a few 10s of EEGs, which outputs band powers and PSDs. It is not easy to understand the data format in the Sqlite database, but it seems to output in a "long" format. Each row is one EEG, one channel, one metric (e.g. P13_20_rel), one 5-second segment. For one EEG with 25 channels, 4 band powers, 240 5-second segments, you get 24,000 measurements. 

How do I get just one simple EEG-level features in an exportable format? I'd like to get  EEG sample rate, length in seconds, channels, EEG start time, number of EEG segments.

I've expanded _CTAP_extract_dataset_info_ into _CTAP_extract_dataset_info2_ that I could contribute as a pull request. The core of it is this:

```
dataset_info2 = struct();
dataset_info2.srate = EEG.srate;
dataset_info2.samples = size(EEG.data,2);
dataset_info2.lengthSeconds = dataset_info2.samples/dataset_info2.srate;
dataset_info2.nbchan = EEG.nbchan;
dataset_info2.startDateTime = EEG.startDateTime;
dataset_info2.segments = length(find(strcmp({EEG.event.type}, 'boundary')))+1;
```
I've spent two days now figuring this out. I've started writing "_export_features_CTAP2_" to get my EEG-level features but it seems to duplicate a lot of the existing code.

**Comment by zenBen** [comment]
Hei Jan. Indeed the wiki links were pointing to the development version, but they are all fixed now? 

Regarding your main problem, a wide-format output of EEG-level features:
A: there were no functions originally for CTAP to do this. `CTAP_export_features()` was designed to produce spectral features of pre-specified segments of EEG, e.g. epochs. `CTAP_extract_dataset_info()` is not a function I wrote but appears to be designed for a limited usecase. 
B. I think you are going in the right direction anyway, repurposing an existing `CTAP_*()` function to operate on features embedded in the EEGLAB struct. Basically, that's how we designed the tool, so that users could use what we give them, and also extend into their own functionality on the basis of the `CTAP_*()` template. That way, you are still using the framework of input and output directories that CTAP sets up, but are free to operate on EEG files as you need. The only restriction is that CTAP works 1 file at a time, so if you need to gather features of all files to compute some group-level statistic, it is better done in another platform, e.g. Stata.
